
version: '3'
services:
  redis:
    build:
      context: . # build的上下文路径
      dockerfile: Dockerfile-redis # Dockerfile文件的路径
      args:
        - datafile=/data/redis
    image: myredis:1.0.2 # 将本次构建内容打包成镜像
    command: ["redis-server", "/data/redis/redis.conf"]