
version: '3'
services:
  redis:
    build:
      context: . # build的上下文路径
      dockerfile: Dockerfile-build # Dockerfile文件的路径
      args:
        - datafile=/data/redis
      # labels: # 貌似目前mac装的不支持
      #   - "com.gyzh.zain.author=Zain"
      #   - "com.gyzh.zain.label-with-empty-value"
    image: myredis:1.0.1 # 将本次构建内容打包成镜像